/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react"
import { useGLTF } from "@react-three/drei/useGLTF"

import params from "../assets/params.json"

const WarehouseSlice = ({ position }) => {
  const { nodes } = useGLTF("models/warehouseSlice.glb")
  return (
    <mesh castShadow receiveShadow position={position} geometry={nodes.Cube001.geometry}>
      <meshPhysicalMaterial metalness={0} roughness={1} reflectivity={1} emissive="black" color={params.sceneColor} />
    </mesh>
  )
}

// useGLTF.preload('/warehouseSlice.glb')

export default WarehouseSlice
