/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { MeshStandardMaterial } from 'three'
import { useGLTF } from '@react-three/drei/useGLTF'

import params from '../assets/params.json'

const WarehouseSlice = ({ position }) => {
	const { nodes } = useGLTF('models/warehouseSlice.glb')
	return <mesh position={position} material={new MeshStandardMaterial({ color: params.sceneColor })} geometry={nodes.Cube001.geometry} />
}

// useGLTF.preload('/warehouseSlice.glb')

export default WarehouseSlice
