/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import params from '../assets/params.json'

const WarehouseSlice = ({ position }) => {
	const { nodes } = useGLTF('models/warehouseSlice.glb')
	return (
		<mesh position={position} geometry={nodes.Cube001.geometry}>
			<meshStandardMaterial color={params.sceneColor}></meshStandardMaterial>
		</mesh>
	)
}

// useGLTF.preload('/warehouseSlice.glb')

export default WarehouseSlice
